 name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Docker container
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: yourdockerhubusername/yourimage:latest
          builder: docker://docker.io/library/docker

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: main
