name: Deploy para o GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código
      uses: actions/checkout@v2
    - name: Configurar ambiente Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Instalar pacotes
      run: |
        npm install
    - name: Construir o site
      run: |
        npm run build
    - name: Publicar no GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.URIEL_TOKEN }}
        publish_dir: ./build
    - name: Executar main.py
      run: |
        python main.py
